name: examen_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Gesti√≥n de estado
  provider: ^6.1.1      # Para el chat (ChangeNotifier)
  get: ^4.6.6           # Para la calculadora (GetX)
  
  # HTTP requests
  http: ^1.2.0          # Para llamadas a la API (yesno.wtf)
  
  # Formateo y utilidades
  intl: ^0.19.0         # Para formatear fechas y horas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets para el chat (fondo)
  assets:
  - assets/images/chat_bg.png
  - assets/images/yes.gif
  - assets/images/no.gif
  - assets/images/maybe.gif